### ISSUE TITLE
fs-promise depreciated

### ISSUE THREAD

**Issue by ucipass** [alexbbt/read-last-lines#11]
I was just wondering if you have any plans to replace fs-promise. I get security audit alerts for this.

This package has been deprecated
Author message: Use mz or fs-extra^3.0 with Promise Support

BTW, I love this module.

**Comment by alexbbt** [comment]
Thanks for the comments! I am glad you like the module

**Comment by alexbbt** [comment]
I have published version 1.5.0 with these changes
