### ISSUE TITLE
what does `lines.length > self.stat.size` means ?

### ISSUE THREAD

**Issue by yeongjet** [alexbbt/read-last-lines#18]
In src/index.js，I found this section in function `do_while_loop`:
```
if (lines.length > self.stat.size) {
	lines = lines.substring(lines.length - self.stat.size);
}
```
In my view, the file's size would never less than the line's length, when is this condition  established?

**Comment by alexbbt** [comment]
That is a weird section, and I wish I had added a comment when I added it. I remember hitting this when first creating the library but I am not sure if it is still a valid case. Ill try to add a test for it later

**Comment by yeongjet** [comment]
Got it

**Comment by alexbbt** [comment]
Hello @yeongjet, Thank you for pointing this out. It turns out this case only applied in a very early version of the library when it had a bug that would go  into negative indexes. I will remove the check in a future version.
