### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by mostfurious** [alexbbt/read-last-lines#22]
Hello,
I just wander if im missing something or is this how its suppose to work.
Im using chokidar to watch on the file change and once that happens use read-last-lines to get the new data:

`chokidar.watch('log.log').on('change', (event, path) => {
    readLn.read('log.log', 1)
    .then((lines) => console.log(lines));
  });`
This works fine for the first change of the file after that it keeps returning empty strings.

**Comment by alexbbt** [comment]
Yeah, that seems strange, do you mind providing an example repo? Then I can try to debug it.

**Comment by mostfurious** [comment]
Windows 10, v1607
Node version: v8.12.0

test.js content:

`const chokidar = require('chokidar');
const readLn = require('read-last-lines');
chokidar.watch('log.log').on('change', (event, path) => {
    console.log("file changed")
    readLn.read('log.log', 1)
    .then((lines) => console.log(lines));
  });`

log.log content before starting the test.js file:

`127.2.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.0.0.3 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747`

After the start i have log.log open and manualy copy/paste the last line "127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747" and then press ctrl+s to save file.

Console log output:

`PS D:\Desktop\node> node .\test.js
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747

127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747




`
log.log content:
`127.2.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.0.0.3 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747`

**Comment by alexbbt** [comment]
I just ran this my self and it worked as expected.

## test.js
``` Javascript
const chokidar = require("chokidar");
const readLn = require("../");

chokidar.watch("log.log").on("change", (event, path) => {
	console.log("file changed");
	readLn.read("log.log", 1).then((lines) => console.log(lines));
});
```

## log.log
```
127.2.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.0.0.3 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
```

I pasted this line and saved over and over and this was the output

## Console Output:
```
$ node test.js 
file changed
127.2.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.0.0.3 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747

file changed
127.2.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.0.0.3 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747

file changed
127.2.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.0.0.3 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747

file changed
127.2.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.0.0.3 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747 127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747

file changed
127.3.0.1 - - [03/Nov/2019:09:16:40 +0200] "GET /wp-admins/js/customize-controls.minx.js?ver=7.2.5 HTTP/1.1" 200 28747
``` 


Can you please check that you are on the latest version of the library?

Can you increase the number of lines you are requesting? I think it is showing you the last empty line rather than the last line with data. The library automatically ignores the last empty line which is the expected format of a log file, but if there are two empty lines, you would recieve that empty line rather than your data.

I did my testing on MacOS. I have not tested this on windows before.

**Comment by TonyBrobston** [comment]
I'm also having the same problem. When printing one line I get two lines; the first line is the content I'm expecting and the second line is just an empty string.

Here's a commit you could test off of.

https://github.com/TonyBrobston/logs-to-mqtt-publisher/tree/e9d093d87929ec07a593a30aca54caf3e846a513

To get this running you'll need to:
clone
run `yarn`
set an environment variable for `FILE_PATH` (I set this to /tmp/blah.log)
run `yarn start`
append to a file like `echo "derp" >> /tmp/blah.log`

**Comment by artemdudkin** [comment]
The same problem I guess I have.

I wanted to get 10 last lines from file at Windows, and got only 5 lines. The reason is EOL at Windows is \r\n while you split lines by \r or \n, so your splitter adds empty line after any line from Windows-generated file.

Some testcase:
`const endOfLine = require('os').EOL;
let text = '';
for (var i=1; i<=10; i++) text = text + i + endOfLine; 
fs.writeFileSync( './test', text);

//fs.writeFileSync( './test', '1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10\r\n'); // for windows
//fs.writeFileSync( './test', '1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n'); // for linux

readLastLines.read('./test', 10).then(res => console.log(res));`

This code will output 10 lines at linux and only 5 lines at Windows (i.e. digits from 6 to 10).

**Comment by alexbbt** [comment]
This makes a lot of sence. I have never tested this on windows before. Can you please run the unit tests on your computer and see if they pass? I will try to test on windows also and will come up with a solution.

**Comment by alexbbt** [comment]
Checkout My PR linked above. I will finish testing and merge this tomorrow

**Comment by artemdudkin** [comment]
For current code base:

>> C:\Users\A\src\_github\read-last-lines>npm run test
>
>> read-last-lines@1.7.1 test C:\Users\A\src\_github\read-last-lines
>> mocha --reporter spec
>
>
>
>
>  #read
>    1) return all lines when asked for more than the file has
>    2) return last line when asked for 1
>    √ return last 2 lines when asked for 2
>    √ return last 2 lines when asked for 2 and missing trailing new line
>    √ Expect and error to be thrown if the file does not exist
>    √ should the new line characters used by the file, when using non standard new line characters
>    3) should return a buffer, when asked for
>    √ should return binary encoding, when asked for
>    √ should correctly read UTF-8 files
>    √ should error if the encoding is invalid
>
>
>  7 passing (134ms)
>  3 failing
>
>  1) #read
>       return all lines when asked for more than the file has:
>
>      AssertionError: expected 16 to equal 11
>      + expected - actual
>
>      -16
>      +11
>
>      at C:\Users\A\src\_github\read-last-lines\test\index.spec.js:18:23
>
>  2) #read
>       return last line when asked for 1:
>
>      AssertionError: expected 0 to equal 3
>      + expected - actual
>
>      -0
>      +3
>
>      at C:\Users\A\src\_github\read-last-lines\test\index.spec.js:28:36
>
>  3) #read
>       should return a buffer, when asked for:
>     AssertionError: expected <Buffer e4 b8 ad e6 96 87 20 65 73 70 61 c3 b1 6f 6c 20 64 65 75 74 73 >63 68 20 65 6e 67 6c 69 73 68 20 e0 a4 b9 e0 a4 bf e0 a4 a8 e0 a5 8d e0 a4 a6 e0 a5 80 ... 114 more >bytes> to have a length of 163 but got 164
>      at C:\Users\A\src\_github\read-last-lines\test\index.spec.js:64:27
>
>
>
>npm ERR! code ELIFECYCLE
>npm ERR! errno 3
>npm ERR! read-last-lines@1.7.1 test: `mocha --reporter spec`
>npm ERR! Exit status 3
>npm ERR!
>npm ERR! Failed at the read-last-lines@1.7.1 test script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\A\AppData\Roaming\npm-cache\_logs\2020-01-13T20_03_30_822Z->debug.log
>
>C:\Users\A\src\_github\read-last-lines>

**Comment by artemdudkin** [comment]
For `fix-windows-bug` branch:

>> read-last-lines@1.7.1 test C:\Users\A\src\_github\read-last-lines
>> mocha --reporter spec
>
>
>
>  #read
>    √ return all lines when asked for more than the file has
>    √ return last line when asked for 1
>    √ return last 2 lines when asked for 2
>    √ return last 2 lines when asked for 2 and missing trailing new line
>    √ Expect and error to be thrown if the file does not exist
>    √ should work with windows new lines
>    1) should return a buffer, when asked for
>    √ should return binary encoding, when asked for
>    √ should correctly read UTF-8 files
>    √ should error if the encoding is invalid
>
>
>  9 passing (45ms)
>  1 failing
>
>  1) #read
>       should return a buffer, when asked for:
>     AssertionError: expected <Buffer e4 b8 ad e6 96 87 20 65 73 70 61 c3 b1 6f 6c 20 64 65 75 74 73 >63 68 20 65 6e 67 6c 69 73 68 20 e0 a4 b9 e0 a4 bf e0 a4 a8 e0 a5 8d e0 a4 a6 e0 a5 80 ... 114 more >bytes> to have a length of 163 but got 164
>      at C:\Users\A\src\_github\read-last-lines\test\index.spec.js:64:27
>
>

**Comment by artemdudkin** [comment]
Yes, it is weird but git client for windows changes `0A` at the end of file `test\utf8` to be `0D 0A`, while git client at ubuntu at VM VirtualBox does not.

**Comment by alexbbt** [comment]
It is strange that the file changes when git client downloads it.

I have finished testing on my own and will publish this new version now

**Comment by alexbbt** [comment]
Here is the new version: https://github.com/alexbbt/read-last-lines/releases/tag/v1.7.1
