### ISSUE TITLE
Promise is pending.

### ISSUE THREAD

**Issue by leftyb** [alexbbt/read-last-lines#4]
Hi, 
When using `read-last-line` in a js script I get no output at all.
From the console I get 
```
readLastLines.read('/home/lefty/version', 1).then( lines => console.log(lines))
Promise { <pending> }
```
Am I doing something wrong? 
Thank you

**Comment by alexbbt** [comment]
Which version of Node are you using? This is written using the ES6 Standard and must be used with Node 6 or above. If you are using it with a lower version, you must transpile it to ES2015.

If you are using Node 6, then can you send a little more of your script?

**Comment by leftyb** [comment]
Hi @alexbbt,

After updating to latest node `v7.4.0` worked properly.
Thank you.
